// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppMVCHON.Models;

#nullable disable

namespace WebAppMVCHON.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251224044316_Std")]
    partial class Std
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppMVCHON.Models.Adhar", b =>
                {
                    b.Property<int>("AdharID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdharID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdharID");

                    b.ToTable("Adhar");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("country");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Lab", b =>
                {
                    b.Property<int>("LabID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabID"));

                    b.Property<int>("PID")
                        .HasColumnType("int");

                    b.Property<int?>("PatientPID")
                        .HasColumnType("int");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LabID");

                    b.HasIndex("PatientPID");

                    b.ToTable("Lab");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Pan", b =>
                {
                    b.Property<int>("PanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PanID"));

                    b.Property<int?>("AdharID")
                        .HasColumnType("int");

                    b.Property<int>("AdharNo")
                        .HasColumnType("int");

                    b.Property<string>("PanUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PanID");

                    b.HasIndex("AdharID");

                    b.ToTable("Pan");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Patient", b =>
                {
                    b.Property<int>("PID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PID");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Result", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarksID")
                        .HasColumnType("int");

                    b.Property<int>("StdRefNo")
                        .HasColumnType("int");

                    b.Property<int?>("StdStudentID")
                        .HasColumnType("int");

                    b.HasKey("ResultID");

                    b.HasIndex("StdStudentID");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.State", b =>
                {
                    b.Property<int>("StataeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StataeID"));

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StataeID");

                    b.HasIndex("CountryID");

                    b.ToTable("state");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Std", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Std");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.UsersTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedUserId");

                    b.ToTable("UsersTask");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Lab", b =>
                {
                    b.HasOne("WebAppMVCHON.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientPID");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Pan", b =>
                {
                    b.HasOne("WebAppMVCHON.Models.Adhar", "Adhar")
                        .WithMany()
                        .HasForeignKey("AdharID");

                    b.Navigation("Adhar");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Result", b =>
                {
                    b.HasOne("WebAppMVCHON.Models.Std", "Std")
                        .WithMany()
                        .HasForeignKey("StdStudentID");

                    b.Navigation("Std");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.State", b =>
                {
                    b.HasOne("WebAppMVCHON.Models.Country", "_Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Country");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.UsersTask", b =>
                {
                    b.HasOne("WebAppMVCHON.Models.Users", "AssignedUser")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("WebAppMVCHON.Models.Users", b =>
                {
                    b.Navigation("AssignedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
